name: Build Electron App
description: Build Electron app from artifact
inputs:
  src-artifact:
    description: Source artifact name
    required: true
  app-id:
    description: App ID
    required: true
  product-name:
    description: Product name
    required: true
  icon-base64:
    description: Icon base64 png
    required: true
  dst-artifact:
    description: Destination artifact name
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: hubol/electric-lizard
    - uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'icon.png'
        fileDir: './'
        encodedString: ${{ inputs.icon-base64 }}
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        cache: 'npm'
    - run: npm ci
      shell: bash
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.src-artifact }}
        path: app
    - run: npm run build
      shell: bash
      env:
        APP_ID: ${{ inputs.app-id }}
        PRODUCT_NAME: ${{ inputs.product-name }}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.dst-artifact }}
        path: dist/win
