parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"iEDX":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.handlePromiseCancellation=exports.CancellationToken=void 0;var e=function(){function e(){this._isCancelled=!1,this._uid=e._counter++}return e.prototype.cancel=function(){this._isCancelled=!0},Object.defineProperty(e.prototype,"isCancelled",{get:function(){return this._isCancelled},enumerable:!1,configurable:!0}),e.prototype.rejectIfCancelled=function(e){this.isCancelled&&e({message:"Cancelled by token",cancellationToken:this})},e._counter=0,e}();function n(e){var n;(null===(n=null==e?void 0:e.reason)||void 0===n?void 0:n.cancellationToken)&&(console.log(e.promise,e.reason),e.preventDefault())}exports.CancellationToken=e,exports.handlePromiseCancellation=n;
},{}],"U54m":[function(require,module,exports) {
"use strict";function e(e,t){return new Promise(function(n,l){null==t||t.rejectIfCancelled(l),setTimeout(function(){null==t||t.rejectIfCancelled(l),n()},e)})}Object.defineProperty(exports,"__esModule",{value:!0}),exports.sleep=void 0,exports.sleep=e;
},{}],"ztjy":[function(require,module,exports) {
"use strict";var e=this&&this.__awaiter||function(e,t,n,r){return new(n||(n=Promise))(function(o,i){function a(e){try{c(r.next(e))}catch(t){i(t)}}function u(e){try{c(r.throw(e))}catch(t){i(t)}}function c(e){var t;e.done?o(e.value):(t=e.value,t instanceof n?t:new n(function(e){e(t)})).then(a,u)}c((r=r.apply(e,t||[])).next())})},t=this&&this.__generator||function(e,t){var n,r,o,i,a={label:0,sent:function(){if(1&o[0])throw o[1];return o[1]},trys:[],ops:[]};return i={next:u(0),throw:u(1),return:u(2)},"function"==typeof Symbol&&(i[Symbol.iterator]=function(){return this}),i;function u(i){return function(u){return function(i){if(n)throw new TypeError("Generator is already executing.");for(;a;)try{if(n=1,r&&(o=2&i[0]?r.return:i[0]?r.throw||((o=r.return)&&o.call(r),0):r.next)&&!(o=o.call(r,i[1])).done)return o;switch(r=0,o&&(i=[2&i[0],o.value]),i[0]){case 0:case 1:o=i;break;case 4:return a.label++,{value:i[1],done:!1};case 5:a.label++,r=i[1],i=[0];continue;case 7:i=a.ops.pop(),a.trys.pop();continue;default:if(!(o=(o=a.trys).length>0&&o[o.length-1])&&(6===i[0]||2===i[0])){a=0;continue}if(3===i[0]&&(!o||i[1]>o[0]&&i[1]<o[3])){a.label=i[1];break}if(6===i[0]&&a.label<o[1]){a.label=o[1],o=i;break}if(o&&a.label<o[2]){a.label=o[2],a.ops.push(i);break}o[2]&&a.ops.pop(),a.trys.pop();continue}i=t.call(e,a)}catch(u){i=[6,u],r=0}finally{n=o=0}if(5&i[0])throw i[1];return{value:i[0]?i[1]:void 0,done:!0}}([i,u])}}};Object.defineProperty(exports,"__esModule",{value:!0}),exports.wait=void 0;var n=require("./cancellationToken"),r=require("./sleep");function o(){var o=this,i=arguments[0],a=void 0,u=33;return arguments.length>1&&(arguments[1]instanceof n.CancellationToken?a=arguments[1]:u=arguments[1]),arguments.length>2&&(a=arguments[2]),new Promise(function(n){return e(o,void 0,void 0,function(){return t(this,function(e){switch(e.label){case 0:return i()?[3,2]:[4,r.sleep(u,a)];case 1:return e.sent(),[3,0];case 2:return n(),[2]}})})})}exports.wait=o;
},{"./cancellationToken":"iEDX","./sleep":"U54m"}],"gnU0":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Stopwatch=void 0;var e=function(){function e(){this.startedMilliseconds=(new Date).getTime()}return Object.defineProperty(e.prototype,"elapsedMilliseconds",{get:function(){return(new Date).getTime()-this.startedMilliseconds},enumerable:!1,configurable:!0}),Object.defineProperty(e.prototype,"elapsedMillisecondsText",{get:function(){return this.elapsedMilliseconds+"ms"},enumerable:!1,configurable:!0}),e}();exports.Stopwatch=e;
},{}],"RfZy":[function(require,module,exports) {
"use strict";function e(e){return e=t(e," "),e=t(e,"_"),r(e=t(e,"-"))}function r(e){return e.charAt(0).toUpperCase()+e.slice(1)}function t(e,r){for(var t=-1;-1!==(t=e.indexOf(r));)e=o(e,t);return e}function o(e,r){var t=e.charAt(r+1).toUpperCase();return e.slice(0,r)+t+e.slice(r+2)}Object.defineProperty(exports,"__esModule",{value:!0}),exports.toPascalCase=void 0,exports.toPascalCase=e;
},{}],"HErv":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.toPascalCase=exports.Stopwatch=exports.wait=exports.sleep=exports.handlePromiseCancellation=exports.CancellationToken=void 0;var e=require("./cancellationToken");Object.defineProperty(exports,"CancellationToken",{enumerable:!0,get:function(){return e.CancellationToken}}),Object.defineProperty(exports,"handlePromiseCancellation",{enumerable:!0,get:function(){return e.handlePromiseCancellation}});var t=require("./sleep");Object.defineProperty(exports,"sleep",{enumerable:!0,get:function(){return t.sleep}});var r=require("./wait");Object.defineProperty(exports,"wait",{enumerable:!0,get:function(){return r.wait}});var n=require("./stopwatch");Object.defineProperty(exports,"Stopwatch",{enumerable:!0,get:function(){return n.Stopwatch}});var o=require("./toPascalCase");Object.defineProperty(exports,"toPascalCase",{enumerable:!0,get:function(){return o.toPascalCase}});
},{"./cancellationToken":"iEDX","./sleep":"U54m","./wait":"ztjy","./stopwatch":"gnU0","./toPascalCase":"RfZy"}],"FT5O":[function(require,module,exports) {

var t,e,n=module.exports={};function r(){throw new Error("setTimeout has not been defined")}function o(){throw new Error("clearTimeout has not been defined")}function i(e){if(t===setTimeout)return setTimeout(e,0);if((t===r||!t)&&setTimeout)return t=setTimeout,setTimeout(e,0);try{return t(e,0)}catch(n){try{return t.call(null,e,0)}catch(n){return t.call(this,e,0)}}}function u(t){if(e===clearTimeout)return clearTimeout(t);if((e===o||!e)&&clearTimeout)return e=clearTimeout,clearTimeout(t);try{return e(t)}catch(n){try{return e.call(null,t)}catch(n){return e.call(this,t)}}}!function(){try{t="function"==typeof setTimeout?setTimeout:r}catch(n){t=r}try{e="function"==typeof clearTimeout?clearTimeout:o}catch(n){e=o}}();var c,s=[],l=!1,a=-1;function f(){l&&c&&(l=!1,c.length?s=c.concat(s):a=-1,s.length&&h())}function h(){if(!l){var t=i(f);l=!0;for(var e=s.length;e;){for(c=s,s=[];++a<e;)c&&c[a].run();a=-1,e=s.length}c=null,l=!1,u(t)}}function m(t,e){this.fun=t,this.array=e}function p(){}n.nextTick=function(t){var e=new Array(arguments.length-1);if(arguments.length>1)for(var n=1;n<arguments.length;n++)e[n-1]=arguments[n];s.push(new m(t,e)),1!==s.length||l||i(h)},m.prototype.run=function(){this.fun.apply(null,this.array)},n.title="browser",n.env={},n.argv=[],n.version="",n.versions={},n.on=p,n.addListener=p,n.once=p,n.off=p,n.removeListener=p,n.removeAllListeners=p,n.emit=p,n.prependListener=p,n.prependOnceListener=p,n.listeners=function(t){return[]},n.binding=function(t){throw new Error("process.binding is not supported")},n.cwd=function(){return"/"},n.chdir=function(t){throw new Error("process.chdir is not supported")},n.umask=function(){return 0};
},{}],"uoss":[function(require,module,exports) {
var process = require("process");
var e=require("process"),n=this&&this.__assign||function(){return(n=Object.assign||function(e){for(var n,r=1,t=arguments.length;r<t;r++)for(var o in n=arguments[r])Object.prototype.hasOwnProperty.call(n,o)&&(e[o]=n[o]);return e}).apply(this,arguments)};Object.defineProperty(exports,"__esModule",{value:!0});var r=require("pissant");function t(e){return JSON.parse(JSON.stringify(e))}function o(e,n){for(var r=[e];r.length>0;){i(r.pop(),n).forEach(function(e){return r.push(e)})}return e}function i(e,n){var r=[];if(Array.isArray(e)&&e.forEach(function(e){return r.push(e)}),"object"==typeof e){delete e[n];for(var t=Object.keys(e),o=0;o<t.length;o++)r.push(e[t[o]])}return r}function u(){return{beforeLoadLevel:function(e,n){return n._ogmo?n._ogmo:n},beforeSaveLevel:function(e,r){var i=t(r);return n(n({width:r.width,height:r.height},r.values),{entities:l(a(function(e){return e.entities},r.layers)),_ogmo:o(o(i,"_name"),"_contents")})}}}function a(e,n){var r=n||this;if(null===r)throw new TypeError("Array.prototype.flatMap called on null or undefined");if("function"!=typeof e)throw new TypeError(e+" is not a function");for(var t=[],o=Object(r),i=o.length>>>0,u=0;u<i;++u)if(u in o){var a=e.call(r,o[u],u,o);t=t.concat(a)}return t}function f(e,n){var t,o,i=(null===(t=null==e?void 0:e.values)||void 0===t?void 0:t.name)?null===(o=null==e?void 0:e.values)||void 0===o?void 0:o.name:""+r.toPascalCase(e.name);return 0===n?i:i+"_"+n}function l(e){for(var r={},t=0;t<e.length;t++){for(var o=e[t],i=0,u=f(o,0);u in r;)u=f(o,++i);r[u]=n({type:o.name,x:o.x,y:o.y,width:o.width,height:o.height},o.values)}return r}console.log("fuck you",this,window),window.stupidMotherFucker=u;
},{"pissant":"HErv","process":"FT5O"}]},{},["uoss"], null);window.stupidMotherFucker();
