name: Push and deploy(?) IguaRPG
on: [push]
jobs:
  push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Dockerfile
        uses: ./
        args:
          - /github/workspace/dist
      - run: pwd
      - run: ls
      - run: ls ./src
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist
